version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercepass
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
